--
-- PostgreSQL database dump
--

\restrict A5BnRstDFdahYmpVJNXNquJTVawyNrWSgGDomdN1yNvPHvaFvNCk03RAi2jpS0A

-- Dumped from database version 16.10 (Debian 16.10-1.pgdg13+1)
-- Dumped by pg_dump version 16.10 (Debian 16.10-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: app
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO app;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: app
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: job_part_jointable; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.job_part_jointable (
    id integer NOT NULL,
    quantity integer,
    job_id integer NOT NULL,
    product_id integer NOT NULL
);


ALTER TABLE public.job_part_jointable OWNER TO app;

--
-- Name: job_part_jointable_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.job_part_jointable ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_part_jointable_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: job_status; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.job_status (
    id smallint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.job_status OWNER TO app;

--
-- Name: jobs; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.jobs (
    id integer NOT NULL,
    customer_name character varying(255),
    customer_phone character varying(255),
    date timestamp(6) without time zone,
    job_description character varying(255),
    price_per_minute double precision,
    title character varying(255),
    work_time_minutes integer,
    status_id smallint NOT NULL
);


ALTER TABLE public.jobs OWNER TO app;

--
-- Name: jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.products (
    id integer NOT NULL,
    "EAN" character varying(255),
    name character varying(255),
    price double precision,
    "productNumber" character varying(255),
    category character varying(255)
);


ALTER TABLE public.products OWNER TO app;

--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: job_part_jointable; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.job_part_jointable (id, quantity, job_id, product_id) FROM stdin;
\.


--
-- Data for Name: job_status; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.job_status (id, name) FROM stdin;
1	notDelivered
2	delivered
3	inProgress
4	missingPart
5	finished
6	pickedUp
\.


--
-- Data for Name: jobs; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.jobs (id, customer_name, customer_phone, date, job_description, price_per_minute, title, work_time_minutes, status_id) FROM stdin;
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.products (id, "EAN", name, price, "productNumber", category) FROM stdin;
\.


--
-- Name: job_part_jointable_id_seq; Type: SEQUENCE SET; Schema: public; Owner: app
--

SELECT pg_catalog.setval('public.job_part_jointable_id_seq', 1, false);


--
-- Name: jobs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: app
--

SELECT pg_catalog.setval('public.jobs_id_seq', 1, false);


--
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: app
--

SELECT pg_catalog.setval('public.products_id_seq', 1, false);


--
-- Name: job_part_jointable job_part_jointable_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.job_part_jointable
    ADD CONSTRAINT job_part_jointable_pkey PRIMARY KEY (id);


--
-- Name: job_status job_status_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.job_status
    ADD CONSTRAINT job_status_pkey PRIMARY KEY (id);


--
-- Name: jobs jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: job_status ukryswvbjv9ks4mumwl2apywndq; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.job_status
    ADD CONSTRAINT ukryswvbjv9ks4mumwl2apywndq UNIQUE (name);


--
-- Name: job_part_jointable fk5f0hi244pf9u22rf7sronksh9; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.job_part_jointable
    ADD CONSTRAINT fk5f0hi244pf9u22rf7sronksh9 FOREIGN KEY (job_id) REFERENCES public.jobs(id);


--
-- Name: job_part_jointable fkm7ppdpbap4avia8vln7saa97w; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.job_part_jointable
    ADD CONSTRAINT fkm7ppdpbap4avia8vln7saa97w FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: jobs fkqqvv6xvt62jn474t0ouwd9w0o; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT fkqqvv6xvt62jn474t0ouwd9w0o FOREIGN KEY (status_id) REFERENCES public.job_status(id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: app
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


--
-- PostgreSQL database dump complete
--

\unrestrict A5BnRstDFdahYmpVJNXNquJTVawyNrWSgGDomdN1yNvPHvaFvNCk03RAi2jpS0A

