package mainProgram.table; // Project Organization

/* --- Imports --- */
import jakarta.persistence.*;

/* --- JobPart Entity --- */
// Represents a join table linking Jobs and Products.
// Stores how many units of a product were used for a specific job.
@Entity // Marks this class as a JPA entity mapped to a database table
@Table(name = "job_part_jointable") // Defines the name of the join table in the database
public class JobPart {
    /// Attributes

    // Primary key - Unique ID for each record in the join table
    @Id // Indicates this field is the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-increment generated by the database
    private int id;

    // Job relationship (many JobPart entries can reference one Job)
    @ManyToOne // Defines a many-to-one relation with Job
    @JoinColumn(name = "job_id", nullable = false) // Foreign key column linking to Job table (required field)
    private Job job;

    // Product relationship (many JobPart entries can reference one Product)
    @ManyToOne // Defines a many-to-one relation with Product
    @JoinColumn(name = "product_id", nullable = false) // Foreign key column linking to Product table (required field)
    private Product product;

    // Number of units of this product used in the job
    private Integer quantity;

    /// Constructors

    // Constructor used when creating a JobPart manually
    public JobPart(Job job, Product product, Integer quantity) {
        this.job = job;
        this.product = product;
        this.quantity = quantity;
    }

    // Default constructor required by JPA
    public JobPart() {
    }

    /// Methods

    // Increases the quantity by a given amount (helper method for updating usage)
    public void addQuantity(int amount) {
        this.quantity += amount;
    }

    /// Getters

    // Gets the unique ID of the JobPart
    /** @return the unique JobPart ID **/
    public int getId() {
        return id;
    }

    // Gets the job connected to this record
    /** @return the Job linked to this JobPart **/
    public Job getJob() {
        return job;
    }

    // Gets the product connected to this record
    /** @return the Product linked to this JobPart **/
    public Product getProduct() {
        return product;
    }

    // Gets how many units of this product are used in the job
    /** @return number of products used **/
    public Integer getQuantity() {
        return quantity;
    }

    /// Setters

    // Sets the Job for this JobPart
    /** @param job the Job to link **/
    public void setJob(Job job) {
        this.job = job;
    }

    // Sets the Product for this JobPart
    /** @param product the Product to link **/
    public void setProduct(Product product) {
        this.product = product;
    }

    // Sets how many units of the product are used
    /** @param quantity number of units **/
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
}
