package mainProgram.table; // Project Organization

/* --- Imports --- */
import jakarta.persistence.*;

/* --- JobServices Entity --- */
// Represents the many-to-many link between Jobs and Services.
// Stores which service was used in a job and the quantity applied.
@Entity // Marks this as a JPA entity mapped to a table
@Table(name = "job_services_jointable") // Specifies the join table name for Job–Service relation
public class JobServices {
    /// Attributes
    // Primary key - Unique ID for each join entry
    @Id // Indicates this field is the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-increment generated by the database
    private int id;

    // Reference to the Job (many entries can relate to the same job)
    @ManyToOne(optional = false) // Relationship: Multiple JobServices can reference one Job
    @JoinColumn(name = "job_id") // Foreign key linking to Job table
    private Job job;

    // Reference to the Service (many entries can relate to the same service)
    @ManyToOne(optional = false) // Relationship: Multiple JobServices can reference one Service
    @JoinColumn(name = "service_id") // Foreign key linking to Services table
    private Services service;

    // Number of times this service was performed
    @Column(nullable = false) // Must always have a value (cannot be null)
    private int quantity;

    /// Constructors

    // Used to create a JobServices record with required values
    public JobServices(Job job, Services service, Integer quantity) {
        this.job = job;
        this.service = service;
        this.quantity = quantity;
    }

    // Default constructor required by JPA
    public JobServices() {
    }

    /// Methods

    // Increase service quantity by a given amount
    /** @param qty amount to add **/
    public void addQuantity(int qty) {
        this.quantity += qty;
    }

    /// Getters

    // Gets the unique ID of this JobService link.
    /** @return the unique JobService ID **/
    public int getId() {
        return id;
    }

    // Gets the Job attached to this record.
    /** @return the linked Job **/
    public Job getJob() {
        return job;
    }

    // Gets the Service used in the Job.
    /** @return the linked Service **/
    public Services getService() {
        return service;
    }

    // Gets how many times the service was applied.
    /** @return number of service units **/
    public int getQuantity() {
        return quantity;
    }

    /// Setters

    // Sets the Job for this link.
    /** @param job the Job to assign **/
    public void setJob(Job job) {
        this.job = job;
    }

    // Sets the Service for this link.
    /** @param service the Service to assign **/
    public void setService(Services service) {
        this.service = service;
    }

    // Sets how many times this service was used.
    /** @param quantity amount used **/
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
}
