package mainProgram.table; // Project Organization

/* --- Imports --- */
import java.util.ArrayList;
import java.util.List;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/* --- Product Class --- */
@Entity
@Table(name = "products")
public class Product {
    // Attributes
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Assumes serial/bigserial PK
    private int id;                      // Maps to: id (Generated by Default as Identity)
    @Column(name = "\"productNumber\"")
    private String productNumber;        // Maps to: productNumber (Not product_number)
    private String name;                 // Maps to: name
    @Column(name = "\"EAN\"")
    private String EAN;                  // Maps to: EAN (Not ean)
    @Column(name = "category")
    private String type;                 // Maps to: category (Not type)
    private Integer price;                // Maps to: price

    /*
    // One-to-Many Relationship: One Product can be associated with many JobParts.
    /**
     * @mappedBy "product"
     * Indicates that the JobPart entity owns the relationship
     * through its "product" field. This makes it a bidirectional
     * relationship where JobPart has the foreign key.
     *
     * @cascade CascadeType.ALL
     * All JPA operations (persist, merge, remove, refresh, detach)
     * performed on this Product will cascade to associated JobParts.
     * EXAMPLE: Deleting a Product will also delete all its JobParts.
     *
     * @orphanRemoval true
     * If a JobPart is removed from this list, it will be automatically
     * deleted from the database. This ensures no orphaned JobPart records
     * exist without a parent Product.
    **/
    //@OneToMany(mappedBy = "product", cascade = CascadeType.ALL, orphanRemoval = true)
    //private List<JobPart> jobParts = new ArrayList<>();

    // Constructor
    public Product(String productNumber, String name, String EAN, String type, Integer price) {
        this.productNumber = productNumber;
        this.name = name;
        this.EAN = EAN;
        this.type = type;
        this.price = price;
    }

    // No-Parameter constructor required by JPA/Hibernate, when fetching Product objects from the database
    public Product() {}

    // Methods
    // Getters
    public String getProductNumber() {
      return productNumber;
    }

    public String getName() {
          return name;
    }

    public String getEAN() {
          return EAN;
      }

    public String getType() {
      return type;
    }

    public Integer getPrice() {
      return price;
    }

    // Setters
    public void setProductNumber(String productNumber) {
        this.productNumber = productNumber;
    }

    public void setName(String name) {
          this.name = name;
      }

    public void setEAN(String EAN) {
          this.EAN = EAN;
      }

    public void setType(String type) {
          this.type = type;
      }

    public void setPrice(Integer price) {
        this.price = price;
    }
}
