package mainProgram.table; // Project Organization

/* --- Imports --- */
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;

/* --- Product Entity --- */
// Represents a product (part) stored in the system.
// Maps to the "products" table in the database.
@Entity // Marks this class as a JPA entity
@Table(name = "products") // Explicit name of the table
public class Product {
    /// Attributes

    // Primary key - Unique ID for each product
    @Id // Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-increment generated by the database
    private int id;

    // Product ID
    @Column(name = "\"productNumber\"") // Quoted to preserve casing
    private String productNumber;

    // Product display name
    private String name;

    // EAN barcode value (JSON key is uppercase)
    @JsonProperty("EAN") // Match frontend JSON field name
    @Column(name = "\"EAN\"") // Quoted to preserve casing
    private String EAN;

    // Category of the product
    @Column(name = "category") // Stored as "category" in the database
    private String type;

    // Unit price of the product
    private Double price;

    /// Constructors

    // Used to manually create Product instances
    public Product(String productNumber, String name, String EAN, String type, Double price) {
        this.productNumber = productNumber;
        this.name = name;
        this.EAN = EAN;
        this.type = type;
        this.price = price;
    }

    // No-Parameter constructor required by JPA/Hibernate, when fetching Product objects from the database
    public Product() {
    }

    /// Getters

    // Gets the product ID
    /** @return unique product ID **/
    public int getId() {
        return id;
    }

    // Gets the product number
    /** @return product identifier **/
    public String getProductNumber() {
        return productNumber;
    }

    // Gets the product name
    /** @return product name **/
    public String getName() {
        return name;
    }

    // Gets the EAN
    /** @return EAN barcode **/
    public String getEAN() {
        return EAN;
    }

    // Gets the product type
    /** @return product category **/
    public String getType() {
        return type;
    }

    // Gets the unit price
    /** @return product price **/
    public Double getPrice() {
        return price;
    }

    /// Setters

    // Sets the product number
    /** @param productNumber identifier to assign **/
    public void setProductNumber(String productNumber) {
        this.productNumber = productNumber;
    }

    // Sets the product name
    /** @param name the name to assign **/
    public void setName(String name) {
        this.name = name;
    }

    // Sets the EAN value
    /** @param EAN EAN barcode to assign **/
    public void setEAN(String EAN) {
        this.EAN = EAN;
    }

    // Sets the product type
    /** @param type category to assign **/
    public void setType(String type) {
        this.type = type;
    }

    // Sets the product price
    /** @param price price to assign **/
    public void setPrice(Double price) {
        this.price = price;
    }
}
