package mainProgram.table; // Project Organization

/* --- Imports --- */
import jakarta.persistence.*;

/* --- Services Entity --- */
// Represents a service stored in the system.
// Maps to the "services" table in the database.
@Entity // Marks this class as a JPA entity
@Table(name = "services") // Explicit name of the table
public class Services {
    /// Attributes

    // Primary key - Unique ID for each service
    @Id // Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-increment generated by the database
    private int id;

    // Service display name
    private String name;

    // Price of the service
    private double price;

    // Duration of the service in minutes
    private int duration;

    /// Constructors

    // Used to manually create Service instances
    public Services(String name, double price, int duration) {
        this.name = name;
        this.price = price;
        this.duration = duration;
    }

    // No-parameter constructor required by JPA/Hibernate, when fetching Service objects from the database
    public Services() {
    }

    /// Getters

    // Gets the service ID
    /** @return unique service ID **/
    public int getId() {
        return id;
    }

    // Gets the name of the service
    /** @return service name **/
    public String getName() {
        return name;
    }

    // Gets the service price
    /** @return service price **/
    public double getPrice() {
        return price;
    }

    // Gets the service duration
    /** @return duration in minutes **/
    public int getDuration() {
        return duration;
    }

    /// Setters

    // Sets the service ID
    /** @param id identifier to assign **/
    public void setId(int id) {
        this.id = id;
    }

    // Sets the service name
    /** @param name the name to assign **/
    public void setName(String name) {
        this.name = name;
    }

    // Sets the service price
    /** @param price price to assign **/
    public void setPrice(double price) {
        this.price = price;
    }

    // Sets the service duration
    /** @param duration duration in minutes **/
    public void setDuration(int duration) {
        this.duration = duration;
    }
}
