package mainProgram.table; // Project Organization

import jakarta.persistence.*;

// Service Class
@Entity
@Table(name = "service")
public class Services {

    // Attributes
    @Id // Marks this field as the table's primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Assumes serial/bigserial PK
    private Integer id; // Maps to: id (Generated by Default as Identity)

    private String name;
    private Double price;
    private Integer duration;

    // Constructor
    public Services(String name, Double price, Integer duration) {
        this.name = name;
        this.price = price;
        this.duration = duration;
    }

    public Services() {

    }

    // Getters
    public String getName() {
        return name;
    }

    public Double getPrice() {
        return price;
    }

    public Integer getDuration() {
        return duration;
    }

    public Integer getId() {
        return id;
    }

    // Setters
    public void setName(String name) {
        this.name = name;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    public void setId(Integer id) {
        this.id = id;
    }
}
