package mainProgram.table; // Project Organization

/* --- Imports --- */
import jakarta.persistence.*;

/* --- Services Class --- */
// Represents a service in the system.
// This entity is mapped to the "services" table in the database.
// Each Service can be linked to jobs or job parts (future expansion if needed).
@Entity                   // Marks this class as a JPA entity (maps to a database table)
@Table(name = "services") // Explicitly sets the table name in the database
public class Services {
    // Attributes
    @Id // Marks this field as the table's primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-incremented ID
    private int id; // Maps to: id (Generated by default as Identity)

    private String name;  // Name of the service
    private double price; // Price of the service
    private int duration; // Duration of the service in minutes

    // Constructor
    // (OPTIONAL) Constructor for manually creating a Service object
    public Services(String name, double price, int duration) {
        this.name = name;
        this.price = price;
        this.duration = duration;
    }

    // No-parameter constructor required by JPA/Hibernate
    // This constructor is used when fetching Service objects from the database
    public Services() {
    }

    // Getters
    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public double getPrice() {
        return price;
    }

    public int getDuration() {
        return duration;
    }

    // Setters
    public void setId(int id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public void setDuration(int duration) {
        this.duration = duration;
    }
}
